### ISSUE TITLE
Ghost handle positioning and effects

### ISSUE THREAD

**Issue by nguyenj** [polleverywhere/sordid-dragon#1]
![screencast 2016-03-02 16-09-39](https://cloud.githubusercontent.com/assets/1127677/13480293/a9e1a070-e091-11e5-842d-c3ef5204c668.gif)

The drag and drop handle ghost goes back to the original position rather than to the new position. Is there a way for the ghost handle to transition to the new position?

**Comment by thoughtless** [comment]
I'm not sure. We could try removing the custom ghost code for IE8/9 and see if that helps.

**Comment by thoughtless** [comment]
@nguyenj Could you test again on version 2.0.1 and see if that resolves the issue?

**Comment by steel** [comment]
@nguyenj is this part of your recent commits? Can you close this if its done?

**Comment by nguyenj** [comment]
Actually wait, this is @adam-h  fix; not mine.

**Comment by nguyenj** [comment]
https://github.com/polleverywhere/sordid-dragon/pull/5

**Comment by adam-h** [comment]
Fixed :)
